[package]
name = "bmidi"
version = "0.0.2"
authors = ["Benedikt Reinartz <filmor@gmail.com>"]

license = "LGPL-3.0"

description = "Midi parsing and processing library"
repository = "https://github.com/filmor/bmidi"

readme = "README.md"


[dependencies]
pitch_calc = "0.11.0"
